version: '3'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: db
    ports:
      - "5432:5432"
  server:
    build: ./server
    ports:
      - "3001:3001"
    depends_on:
      - postgres

  client:
    build: ./client
    ports:
      - "3000:3000"
    depends_on:
      - server
